on:
  issues:
    types: [opened]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        run: gh issue close "$NUMBER" -c "Please re-open the issue in the [GLIM main repository](https://github.com/koide3/glim/issues)."
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
